const intro=document.getElementById('intro');document.getElementById('enter').onclick=()=>intro.classList.add('hide');
const c=document.getElementById('stars'),x=c.getContext('2d');let stars=[];function resize(){c.width=innerWidth;c.height=innerHeight;stars=Array.from({length:Math.min(220,innerWidth/5)},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*1.4+.2,a:Math.random(),s:Math.random()*.004+.001}))}function draw(){x.clearRect(0,0,c.width,c.height);stars.forEach(s=>{s.a+=s.s;if(s.a>1||s.a<.1)s.s*=-1;x.globalAlpha=s.a;x.fillStyle='#fff';x.beginPath();x.arc(s.x,s.y,s.r,0,7);x.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
const data=[['Open when you are stressed','Pahadan, breathe. You do not have to solve your entire life tonight. Eat something, drink water, sleep. Tomorrow can wait until tomorrow.'],['Open when CAT feels impossible','I will always want to see you achieve what you are working for. But a score cannot make you more Anushka, and it cannot make you less Anushka. I believe in the person doing the work, not only the result.'],['Open when you are angry with me','You are allowed to be angry. Love is not an excuse for my mistakes. I want to listen without defending myself, own what I did, and let better actions speak afterward.'],['Open when you miss me','Imagine me showing up just to annoy you, calling you Pahadan until you say “bhaago yha se.” I probably miss you at exactly the same time.'],['Open when you do not feel good enough','You are not a result, a deadline, or everybody else’s expectations. To me you are the laugh, the stubbornness, the softness, the chaos, the strength — the whole person.'],['Open when you need to remember how I see you','Kind. Responsible. Ridiculously pretty. Funny without trying. Strong even when tired. And somehow still the Pahadan who made this Jaat care far more than he planned to.']];
const box=document.getElementById('letters'),modal=document.getElementById('modal');data.forEach((d,i)=>{let b=document.createElement('button');b.innerHTML=d[0]+'<small style="display:block;margin-top:12px;opacity:.45">FROM JAAT → PAHADAN</small>';b.onclick=()=>{document.getElementById('letterTitle').textContent=d[0];document.getElementById('letterBody').textContent=d[1];modal.classList.add('show')};box.appendChild(b)});document.getElementById('close').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};document.getElementById('yes').onclick=()=>document.getElementById('yesScreen').classList.add('show');document.getElementById('second').onclick=()=>alert('Take all the time you need, Pahadan. ❤️');
document.getElementById('sound').onclick=()=>alert('Our soundtrack is waiting below — Hindi + English, chosen for you. ♫');
const memoryFiles=[
"WhatsApp Image 2026-10-02 at 10.26.57 PM.jpeg",
"WhatsApp Image 2026-10-02 at 10.26.57 PM (1).jpeg",
"WhatsApp Image 2026-10-02 at 10.26.58 PM.jpeg",
"WhatsApp Image 2026-10-02 at 10.26.58 PM (1).jpeg",
"WhatsApp Image 2026-10-02 at 10.26.58 PM (2).jpeg",
"WhatsApp Image 2026-10-02 at 10.26.58 PM (3).jpeg",
"WhatsApp Image 2026-10-02 at 10.27.00 PM.jpeg",
"WhatsApp Image 2026-10-02 at 10.27.00 PM (1).jpeg",
"WhatsApp Image 2026-10-02 at 10.27.00 PM (2).jpeg",
"WhatsApp Image 2026-10-02 at 10.27.01 PM.jpeg",
"WhatsApp Image 2026-10-02 at 10.28.23 PM.jpeg",
"WhatsApp Image 2026-10-02 at 10.28.23 PM (1).jpeg",
"WhatsApp Image 2026-10-02 at 10.28.24 PM.jpeg",
"WhatsApp Image 2026-10-02 at 10.28.24 PM (1).jpeg",
"WhatsApp Image 2026-10-02 at 10.28.24 PM (2).jpeg",
"WhatsApp Image 2026-10-02 at 10.28.25 PM.jpeg",
"WhatsApp Image 2026-10-02 at 10.28.25 PM (1).jpeg",
"WhatsApp Image 2026-10-02 at 10.28.25 PM (2).jpeg",
"WhatsApp Image 2026-10-02 at 10.28.25 PM (3).jpeg",
"WhatsApp Image 2026-10-02 at 10.28.26 PM.jpeg"];
const memoryNotes=["That smile in the passenger seat. No grand occasion, no perfect setup — just one of those simple moments with you that I ended up wanting to keep.","Your hand on my head, both of us smiling like idiots. This photo feels like us — comfortable, playful, and completely unserious together.","One of my favourite things about us: even an ordinary plan somehow becomes a memory worth saving.","Somewhere along the way, taking pictures together stopped feeling like documenting a day and started feeling like documenting us.","A night drive, a meeting, a few extra minutes together — I never realised how much I would start valuing the ordinary time with you.","Two people in one frame, and somehow my eyes still go straight to your smile.","I like this one because it doesn't need a story written over it. I was happy to be there with you. That's enough.","Another night, another little piece of us I didn't know would matter this much later.","Just sitting beside you became one of those things that could make an otherwise normal day feel better.","Your hand on my head and that smile — photographic evidence that Pahadan has always had Jaat under control. 😂","Pahadan ka gulaaaam. Pahadan ko salaaaaam. No explanation. The evidence speaks for itself. 😂","You dancing and being completely yourself. I hope life gives you more moments where you forget the pressure and simply enjoy being Anushka.","One mirror, one phone, two people who still hadn't properly named whatever this was.","05 July. Your birthday. I wanted the day to be about you; somehow it became one of the days I wanted to remember too.","This one makes me laugh every time — you holding my face, both of us completely forgetting about posing properly.","A tiny detail from one of our days together. No invented meaning, no dramatic story — I just wanted to keep the memory exactly as it was.","05 July — one of those photographs where I remember the feeling more than the pose.","Not every favourite memory needs to be in focus. Sometimes the blur is proof that we were too busy living it.","Flowers for your birthday. They were only meant to last a few days. The memory deserved longer. 🌸","And one more from your birthday — because apparently I was never going to be able to choose just one."];
const mg=document.getElementById("memoryGrid");
if(mg){memoryFiles.forEach((src,i)=>{const card=document.createElement("figure");card.className="memory-card m"+(i+1);card.innerHTML='<div class="photo-wrap"><img loading="lazy" src="'+encodeURI(src)+'" alt="A memory of Puneet and Anushka"></div><figcaption><small>MEMORY '+String(i+1).padStart(2,"0")+'</small><p>'+memoryNotes[i]+'</p><span>tap to hold this moment ✦</span></figcaption>';card.onclick=()=>card.classList.toggle("open");mg.appendChild(card)})}
