'use client';
import {useState} from 'react';
import {motion,AnimatePresence} from 'framer-motion';
import {Heart,Mail,ChevronDown,X} from 'lucide-react';

const Fade=({children,className=''})=><motion.div className={className} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.8}}>{children}</motion.div>;
const letters=[
['Open when you are stressed','Pahadan, breathe. One exam, one result, one difficult week cannot measure you. Eat something. Drink water. Sleep. You do not have to solve your whole life tonight.'],
['Open when CAT feels impossible','I believe in your effort, not just an outcome. Whatever the score says, you are still Anushka.'],
['Open when you are angry with me','You are allowed to be angry. I do not want affection to become an excuse for my mistakes. I want to listen, own what I did, and do better through actions.'],
['Open when you miss me','Imagine me annoying you and calling you Pahadan until you tell me to bhaago yha se. I miss you too.'],
['Open when you forget how I see you','Kind. Responsible. Ridiculously pretty. Stubborn. Funny without trying. Strong even when you are tired.']
];

export default function LoveStory(){
 const [entered,setEntered]=useState(false),[letter,setLetter]=useState(null),[yes,setYes]=useState(false);
 return <main className="grain soft min-h-screen">
 <AnimatePresence>{!entered&&<motion.div exit={{opacity:0}} className="fixed inset-0 z-50 bg-[#0b090a] flex items-center justify-center px-6"><div className="text-center max-w-xl"><p className="sans text-[11px] tracking-[.4em] uppercase text-white/45 mb-8">For one Pahadan</p><h1 className="text-5xl md:text-7xl glow">Hi, Pahadan.</h1><p className="mt-6 text-white/60 text-lg">I made a little place on the internet that belongs to us.</p><button onClick={()=>setEntered(true)} className="mt-10 rounded-full border border-white/20 px-7 py-3 sans text-sm hover:bg-white hover:text-black transition">Enter our story →</button></div></motion.div>}</AnimatePresence>

 <header className="min-h-screen flex items-center justify-center px-6"><div className="text-center max-w-4xl"><p className="sans uppercase tracking-[.35em] text-[10px] text-white/50 mb-7">To Anushka, from Puneet</p><h1 className="text-5xl md:text-8xl leading-[.95] glow">A Pahadan.<br/>A Jaat.<br/><em className="text-[#e9b8c1]">One very unlikely story.</em></h1><p className="mt-8 text-white/60">It started in a group chat. It definitely did not stay there.</p><ChevronDown className="mx-auto mt-16 opacity-40 heart"/></div></header>

 <section className="py-28 px-6 max-w-4xl mx-auto"><Fade><p className="sans text-xs tracking-[.3em] text-[#dca6b1] uppercase">Chapter I · The beginning</p><h2 className="mt-4 text-4xl md:text-6xl">We met somewhere random.</h2><p className="mt-8 text-xl md:text-2xl leading-relaxed text-white/70">A group chat. Some conversations. Then I said something I should not have about your best friend — and we stopped talking for three months.</p><div className="line my-20"/><p className="text-center text-white/45 sans text-sm">Three months of silence.</p><p className="text-center text-3xl md:text-5xl mt-8">Then, on my birthday…</p><div className="paper rounded-2xl p-8 mt-10 max-w-xl mx-auto"><p className="sans text-xs uppercase tracking-widest text-black/40">New message</p><p className="text-3xl mt-4">“Happy birthday.”</p></div><p className="text-center mt-10 text-2xl text-white/70">It did not feel like we started again.<br/><strong className="text-white">It felt like we simply continued.</strong></p></Fade></section>

 <section className="py-28 px-6 bg-[#f1e9e0] text-[#261a1e]"><div className="max-w-5xl mx-auto"><Fade><Mail className="mb-5"/><p className="sans text-xs tracking-[.3em] uppercase opacity-50">The inbox era</p><h2 className="text-4xl md:text-6xl mt-3">Apparently normal people text.</h2><p className="text-2xl mt-3 italic">Pahadan & Jaat wrote emails.</p><div className="grid md:grid-cols-2 gap-6 mt-14"><div className="paper rounded-2xl p-7"><p className="sans text-xs opacity-40">FROM: Jaat · SUBJECT: Study break? 🎬</p><p className="mt-6 text-xl">“How about we make it a movie date?”</p><p className="mt-6 text-sm opacity-60">P.S. Pahadi girl sounds way better than padhai girl.</p></div><div className="paper rounded-2xl p-7"><p className="sans text-xs opacity-40">FROM: Pahadan</p><p className="mt-6 text-3xl">“Hey Cutie”</p><p className="mt-5 text-2xl">Bhaago yha se.</p></div><div className="paper rounded-2xl p-7 md:col-span-2"><p className="sans text-xs opacity-40">SUBJECT: To my jaat boy</p><p className="mt-6 text-2xl md:text-3xl">“Even on the tired or busy days, I still choose this, and I still choose you.”</p></div></div></Fade></div></section>

 <section className="py-28 px-6 max-w-4xl mx-auto"><Fade><p className="sans text-xs tracking-[.3em] text-[#dca6b1] uppercase">5 July · Her day</p><h2 className="text-5xl md:text-7xl mt-4">Happy birthday, Pahadan.</h2><p className="mt-6 text-xl text-white/65">Flowers, photographs, that smile — and a day that was supposed to be about you becoming one of my favourite memories too.</p></Fade></section>

 <section className="py-28 px-6 bg-[#efe6dd] text-[#25191d]"><div className="max-w-5xl mx-auto"><Fade><p className="sans text-xs tracking-[.3em] uppercase opacity-45">For the girl behind all the expectations</p><h2 className="text-5xl md:text-7xl mt-3">Before there was “us”, there was you.</h2><div className="mt-10 space-y-5 text-xl md:text-2xl leading-relaxed"><p>The eldest child. The responsible one. Preparing for CAT while carrying plans, expectations and a thousand thoughts at once.</p><p className="text-3xl md:text-5xl py-8">I fell for the girl taking the exam.<br/><em className="text-[#8b3e50]">Not the result that comes after it.</em></p><p>You are allowed to rest. You do not have to earn love by getting everything right.</p></div></Fade></div></section>

 <section className="py-28 px-6 max-w-5xl mx-auto"><Fade><p className="sans text-xs tracking-[.3em] text-[#dca6b1] uppercase">Letters for later</p><h2 className="text-5xl md:text-7xl mt-3">Open when…</h2><div className="grid md:grid-cols-2 gap-4 mt-12">{letters.map(l=><button key={l[0]} onClick={()=>setLetter(l)} className="text-left rounded-2xl border border-white/10 p-6 hover:bg-white/5"><Mail/><p className="mt-8 text-2xl">{l[0]}</p><p className="sans text-xs mt-2 opacity-40">From Jaat → Pahadan</p></button>)}</div></Fade></section>

 <section className="py-28 px-6 bg-[#120e10]"><div className="max-w-4xl mx-auto"><Fade><p className="sans text-xs tracking-[.3em] text-[#dca6b1] uppercase">The part I cannot romanticise</p><h2 className="text-4xl md:text-6xl mt-4">I haven't always deserved your trust.</h2><div className="mt-8 text-xl md:text-2xl leading-relaxed text-white/70 space-y-5"><p>I have lied to you. You caught me. I hurt you. And you still gave me chances I did not always deserve.</p><p>I cannot rewrite those moments, and I do not want a beautiful website to pretend they did not happen.</p><p className="text-white">I can only choose honesty now, and keep becoming someone whose actions make your trust feel safe.</p></div></Fade></div></section>

 <section className="py-28 px-6 max-w-4xl mx-auto"><Fade><p className="sans text-xs tracking-[.3em] text-[#dca6b1] uppercase">Our soundtrack</p><h2 className="text-5xl md:text-7xl mt-3">Songs that feel a little like you.</h2><div className="mt-10 space-y-3 sans">{[['Iktara','Kavita Seth'],['Tum Se Hi','Mohit Chauhan'],['Kho Gaye Hum Kahan','Jasleen Royal & Prateek Kuhad'],['Until I Found You','Stephen Sanchez'],['Best Part','Daniel Caesar feat. H.E.R.'],['Yellow','Coldplay']].map(([s,a],i)=><div key={s} className="flex justify-between border-b border-white/10 py-5"><div><p className="text-lg">{String(i+1).padStart(2,'0')} · {s}</p><p className="text-sm text-white/40">{a}</p></div><Heart size={17}/></div>)}</div></Fade></section>

 <section className="min-h-screen flex items-center justify-center px-6 py-28"><Fade className="max-w-3xl text-center"><p className="text-2xl text-white/55">There's one thing I've never actually done.</p><div className="my-12 space-y-4 text-xl md:text-3xl"><p>We've missed each other like a couple.</p><p>Fought like a couple.</p><p>Made memories like a couple.</p><p>Cared like a couple.</p></div><p className="text-2xl text-white/55">But I never actually asked you.</p><h2 className="text-6xl md:text-8xl mt-12 glow">Anushka Dangwal,</h2><p className="text-4xl md:text-6xl mt-5 text-[#e9b8c1]">will you be my girlfriend?</p><div className="mt-12 flex flex-col sm:flex-row justify-center gap-4"><button onClick={()=>setYes(true)} className="rounded-full bg-[#f2d5da] text-[#2a161d] px-9 py-4 sans font-semibold">YES ❤️</button><button className="rounded-full border border-white/20 px-9 py-4 sans">I need a second 🥹</button></div><p className="sans text-[11px] text-white/30 mt-8">No tricks. Your answer is yours.</p></Fade></section>

 <footer className="py-16 text-center text-white/35 sans text-sm">Made by Jaat, for Pahadan.</footer>

 <AnimatePresence>{letter&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/80 p-5 flex items-center justify-center" onClick={()=>setLetter(null)}><div onClick={e=>e.stopPropagation()} className="paper max-w-xl w-full rounded-3xl p-8 relative"><button onClick={()=>setLetter(null)} className="absolute right-5 top-5"><X/></button><p className="sans text-xs uppercase opacity-40">From Jaat · to Pahadan</p><h3 className="text-3xl mt-5">{letter[0]}</h3><p className="text-xl leading-relaxed mt-8">{letter[1]}</p><p className="mt-10 italic">— Puneet</p></div></motion.div>}</AnimatePresence>
 <AnimatePresence>{yes&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-50 bg-[#170c11] flex items-center justify-center p-6"><div className="text-center"><Heart className="mx-auto text-[#e8aeb9]" size={48} fill="currentColor"/><h2 className="text-6xl md:text-8xl mt-6">She said yes.</h2><p className="text-2xl mt-6 text-white/70">Happy Boyfriend's Day to me, I guess. ❤️</p><button onClick={()=>setYes(false)} className="mt-10 sans text-sm border border-white/20 rounded-full px-6 py-3">One more look at our story</button></div></motion.div>}</AnimatePresence>
 </main>
}